testing front and back tests

diff --git a/.github/workflows/sonar-front.yml b/.github/workflows/sonar-front.yml
--- a/.github/workflows/sonar-front.yml
+++ b/.github/workflows/sonar-front.yml
@@ -1,23 +1,64 @@
 name: sonar-frontend
 on:
   push:
-    branches:
-      - main
+    branches: [main, develop-back, develop-front]
   pull_request:
-    types: [opened, synchronize, reopened]
+    branches: [main, develop-back, develop-front]
 jobs:
-  sonarqube:
+  frontend:
     defaults:
       run:
         working-directory: front
-    name: SonarQube
+
+    strategy:
+      matrix:
+        node-version: [ 20 ]
+
+    name: Frontend
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - name: SonarQube Scan
-        uses: SonarSource/sonarqube-scan-action@v5
+          fetch-depth: 0
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+
+      - name: Cache node_modules
+        uses: actions/cache@v4
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: ${{ runner.os }}-node
+
+      - name: Install dependencies
+        run: |
+          npm ci
+          npm install -g @angular/cli
+
+      - name: Run tests with coverage
+        run: ng test --no-watch --code-coverage --browsers=ChromeHeadless | tee test-output.log
+
+      - name: Print test output
+        run: cat test-output.log
+
+      - name: Debug coverage directory
+        run: |
+          echo "Listing all files in coverage/ and coverage/bobapp/"
+          find coverage/ || echo "No coverage directory"
+          find coverage/bobapp/ || echo "No bobapp directory"
+
+      - name: List coverage files
+        run: |
+          ls -R coverage/
+          echo "Content of lcov.info:"
+          cat coverage/*/lcov.info || echo "lcov.info not found"
+
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarcloud-github-action@v2
         with:
           projectBaseDir: front
           args: >
