testing

diff --git a/.github/workflows/tests-quality.yml b/.github/workflows/tests-quality.yml
--- a/.github/workflows/tests-quality.yml
+++ b/.github/workflows/tests-quality.yml
@@ -7,47 +7,47 @@ on:
     branches: [main, develop-back, develop-front]
 
 jobs:
-  backend:
-    defaults:
-      run:
-        working-directory: back
-
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: 'zulu'
-
-      - name: Cache Maven packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-
-      - name: Run Tests and SonarCloud Analysis
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          mvn -B verify sonar:sonar \
-            -Dsonar.projectKey=adThomDev_Gerez-un-projet-collaboratif-en-integrant-une-demarche-CI-CD \
-            -Dsonar.organization=adthomdev \
-            -Dsonar.host.url=https://sonarcloud.io \
-            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+#  backend:
+#    defaults:
+#      run:
+#        working-directory: back
+#
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 0
+#
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v4
+#        with:
+#          java-version: 17
+#          distribution: 'zulu'
+#
+#      - name: Cache Maven packages
+#        uses: actions/cache@v4
+#        with:
+#          path: ~/.m2
+#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: ${{ runner.os }}-m2
+#
+#      - name: Cache SonarCloud packages
+#        uses: actions/cache@v4
+#        with:
+#          path: ~/.sonar/cache
+#          key: ${{ runner.os }}-sonar
+#          restore-keys: ${{ runner.os }}-sonar
+#
+#      - name: Run Tests and SonarCloud Analysis
+#        env:
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#        run: |
+#          mvn -B verify sonar:sonar \
+#            -Dsonar.projectKey=adThomDev_Gerez-un-projet-collaboratif-en-integrant-une-demarche-CI-CD \
+#            -Dsonar.organization=adthomdev \
+#            -Dsonar.host.url=https://sonarcloud.io \
+#            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
 
   frontend:
     defaults:
@@ -82,15 +82,32 @@ jobs:
         run: |
           npm ci
           npm install -g @angular/cli
+          npm install --save-dev nyc
 
       - name: Run tests with coverage
         run: ng test --no-watch --code-coverage --browsers=ChromeHeadless
+
+      - name: Generate lcov.info with nyc
+        run: npx nyc report --reporter=lcov --report-dir=coverage/bobapp
 
       - name: List coverage files
         run: |
           ls -R coverage/
           echo "Content of lcov.info:"
           cat coverage/*/lcov.info || echo "lcov.info not found"
+
+      # - name: Install dependencies
+      #   run: |
+      #     npm ci
+      #     npm install -g @angular/cli
+
+      # - name: Run tests with coverage
+      #   run: ng test --no-watch --code-coverage --browsers=ChromeHeadless
+
+      # - name: List coverage files
+      #   run: |
+      #     ls -R coverage/
+      #     echo "Content of lcov.info:"          cat coverage/*/lcov.info || echo "lcov.info not found"
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@v2
@@ -110,3 +127,4 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
