testing

diff --git a/.github/workflows/tests-quality.yml b/.github/workflows/tests-quality.yml
--- a/.github/workflows/tests-quality.yml
+++ b/.github/workflows/tests-quality.yml
@@ -1,4 +1,4 @@
-name: Backend Tests and SonarCloud
+name: Tests and SonarCloud
 
 on:
   push:
@@ -82,14 +82,32 @@ jobs:
         run: |
           npm ci
           npm install -g @angular/cli
+          npm install --save-dev nyc
 
       - name: Run tests with coverage
         run: ng test --no-watch --code-coverage --browsers=ChromeHeadless
 
+      - name: Generate lcov.info with nyc
+        run: npx nyc report --reporter=lcov --report-dir=coverage/bobapp
+
       - name: List coverage files
         run: |
           ls -R coverage/
-          echo "Content of lcov.info:"          cat coverage/*/lcov.info || echo "lcov.info not found"
+          echo "Content of lcov.info:"
+          cat coverage/*/lcov.info || echo "lcov.info not found"
+
+      # - name: Install dependencies
+      #   run: |
+      #     npm ci
+      #     npm install -g @angular/cli
+
+      # - name: Run tests with coverage
+      #   run: ng test --no-watch --code-coverage --browsers=ChromeHeadless
+
+      # - name: List coverage files
+      #   run: |
+      #     ls -R coverage/
+      #     echo "Content of lcov.info:"          cat coverage/*/lcov.info || echo "lcov.info not found"
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@v2
