testing

diff --git a/.github/workflows/tests-quality.yml b/.github/workflows/tests-quality.yml
--- a/.github/workflows/tests-quality.yml
+++ b/.github/workflows/tests-quality.yml
@@ -92,6 +92,13 @@ jobs:
           echo "Content of lcov.info:"
           cat coverage/*/lcov.info || echo "lcov.info not found"
 
+      - name: Check lcov.info exists and is not empty
+        run: |
+          if [ ! -s coverage/bobapp/lcov.info ]; then
+            echo "lcov.info missing or empty!"
+            exit 1
+          fi
+
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@v2
         with:
@@ -99,14 +106,9 @@ jobs:
           args: >
             -Dsonar.projectKey=adThomDev_Gerez-un-projet-collaboratif-en-integrant-une-demarche-CI-CD
             -Dsonar.organization=adthomdev
-            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
             -Dsonar.sources=src
-            -Dsonar.exclusions=**/*.spec.ts
-            -Dsonar.tests=src
-            -Dsonar.test.inclusions=**/*.spec.ts
-            -Dsonar.test.exclusions=**/node_modules/**
+            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
             -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info
-            -Dsonar.coverage.exclusions=**/*.spec.ts,**/test.ts,**/polyfills.ts
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
